// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBW-qzOOqSjXDQo9twEn6CxT6hWZDHcz0c',
    appId: '1:754685196675:web:846a3ba443a3b473cbdeb6',
    messagingSenderId: '754685196675',
    projectId: 'university-project-ea276',
    authDomain: 'university-project-ea276.firebaseapp.com',
    storageBucket: 'university-project-ea276.appspot.com',
    measurementId: 'G-1KVH3GV76J',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCd_2MDT2vfwm8XYS6ncEIoHrmDiH01y8M',
    appId: '1:754685196675:android:200226cb47996d86cbdeb6',
    messagingSenderId: '754685196675',
    projectId: 'university-project-ea276',
    storageBucket: 'university-project-ea276.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDWWpjRc7B4SJtUt4x8aquMTyZv6yhHXOk',
    appId: '1:754685196675:ios:73bdc39c9d7c2954cbdeb6',
    messagingSenderId: '754685196675',
    projectId: 'university-project-ea276',
    storageBucket: 'university-project-ea276.appspot.com',
    iosBundleId: 'com.example.fluttercourse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDWWpjRc7B4SJtUt4x8aquMTyZv6yhHXOk',
    appId: '1:754685196675:ios:f0fb60169a604604cbdeb6',
    messagingSenderId: '754685196675',
    projectId: 'university-project-ea276',
    storageBucket: 'university-project-ea276.appspot.com',
    iosBundleId: 'com.example.fluttercourse.RunnerTests',
  );
}
